# -*- coding: utf-8 -*-
"""New Model Building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGqNc0pD3XbDFyAuWPNxC93igdBzvkAf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/DatasetMeasles/cleaned_data.csv")

"""Load Dataset"""

df

df.info()

missing_summary = (
    df.isna()
      .sum()
      .reset_index()
      .rename(columns={'index': 'Column', 0: 'Missing_Count'})
)
missing_summary['Missing_%'] = (missing_summary['Missing_Count'] / len(df)) * 100
missing_summary = missing_summary.sort_values(by='Missing_%', ascending=False)

missing_summary

"""Correllation Matrix"""

corr = df.corr(numeric_only=True)

corr

plt.figure(figsize=(14,10))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Numeric Features')
plt.show()

"""GEOGRAPHIC TRENDS"""

plt.figure(figsize=(10,6))
sns.lineplot(data=df, x='Year', y='Reported_measles_cases', hue='Country')
plt.title('Trend of Reported Measles Cases Over Years by Country')
plt.show()

"""FEATURE INTERACTIONS"""

sns.pairplot(df, vars=['MCV1_coverage (%)', 'MCV2_coverage (%)',
                       'Reported_measles_cases', 'Measles_deaths'],
             hue='Outbreak_Label', diag_kind='kde')
plt.show()

from scipy import stats
import numpy as np

z_scores = np.abs(stats.zscore(df.select_dtypes(include=['float64'])))
outliers = (z_scores > 3).sum(axis=0)
pd.DataFrame({'Column': df.select_dtypes(include=['float64']).columns,
              'Outlier_Count': outliers})

"""HANDLE OUTLIERS"""

from scipy.stats.mstats import winsorize
df['GDP_per_capita (US$)'] = winsorize(df['GDP_per_capita (US$)'], limits=[0.05, 0.05])

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)
IQR = Q3 - Q1
df = df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]

df['GDP_per_capita (US$)'] = np.log1p(df['GDP_per_capita (US$)'])

sns.regplot(x='GDP_per_capita (US$)', y='Measles_deaths', data=df)

df.info()

# df = df.drop('Outbreak_alert', axis=1)
df = df.drop('Country', axis=1)
df = df.drop('Year', axis=1)

df['Outbreak_Label'].unique()

mapping = {
    'TRUE': 1,
    'Outbreak': 1,
    'FALSE': 0,
    'Non-outbreak': 0
}

df['Outbreak_Label'] = df['Outbreak_Label'].map(mapping)

"""Modelling"""

from sklearn.preprocessing import LabelEncoder


y = df['Outbreak_Label']


categorical_cols = ['SIAs_in_past_3yrs']


le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col].astype(str))


X = df.drop(columns=['Outbreak_Label'])


X = X.apply(pd.to_numeric, errors='coerce').astype(np.float32)

print(X.dtypes)
print("\nAny NaN left? ", X.isna().sum().sum())

"""**FEature Engineering**"""

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.feature_selection import RFE, mutual_info_classif
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

# Drop Country column
X = df.drop(columns=['Outbreak_Label'])
y = df['Outbreak_Label']


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# === RFE (Recursive Feature Elimination) ===
model = LogisticRegression(max_iter=1000)
rfe = RFE(model, n_features_to_select=10)
rfe.fit(X_scaled, y)

selected_features_rfe = X.columns[rfe.support_]
print("Selected Features by RFE:")
print(selected_features_rfe.tolist(), "\n")

# === PCA (Principal Component Analysis) ===
pca = PCA(n_components=5)
pca.fit(X_scaled)
X_pca = pca.transform(X_scaled)

# Extract top contributing features for each principal component
loading_scores = pd.DataFrame(pca.components_.T,
                              columns=[f'PC{i+1}' for i in range(pca.n_components_)],
                              index=X.columns)

top_features_per_pc = {}
for i in range(pca.n_components_):
    sorted_features = loading_scores.iloc[:, i].abs().sort_values(ascending=False).head(5)
    top_features_per_pc[f'PC{i+1}'] = sorted_features.index.tolist()

print("Top Contributing Features per PCA Component:")
for pc, feats in top_features_per_pc.items():
    print(f"{pc}: {feats}")
print()

# ===  MI (Mutual Information) ===
mi_scores = mutual_info_classif(X_scaled, y)
mi_df = pd.DataFrame({'Feature': X.columns, 'MI_Score': mi_scores})
mi_df = mi_df.sort_values(by='MI_Score', ascending=False)

top_mi_features = mi_df.head(10)
print("Top 10 Features by Mutual Information:")
print(top_mi_features, "\n")

X[selected_features_rfe].info()

le = LabelEncoder()
y_encoded = le.fit_transform(df['Outbreak_Label'])

"""DEEP LEARNING MODEL"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Bidirectional, GRU, Dense
from tensorflow.keras.optimizers import Adam

# --- Split helper ---
def prepare_data(X, y):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y)
    # reshape for LSTM input: [samples, timesteps, features]
    X_train = np.expand_dims(X_train, axis=1)
    X_test = np.expand_dims(X_test, axis=1)
    return X_train, X_test, y_train, y_test

# --- Model builders ---
def build_lstm(input_shape):
    model = Sequential([
        LSTM(64, input_shape=input_shape, activation='tanh'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer=Adam(0.001), loss='binary_crossentropy', metrics=['accuracy'])
    return model

def build_bilstm(input_shape):
    model = Sequential([
        Bidirectional(LSTM(64, activation='tanh'), input_shape=input_shape),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer=Adam(0.001), loss='binary_crossentropy', metrics=['accuracy'])
    return model

def build_gru(input_shape):
    model = Sequential([
        GRU(64, input_shape=input_shape, activation='tanh'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer=Adam(0.001), loss='binary_crossentropy', metrics=['accuracy'])
    return model

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score
import joblib
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# --- Meta learner setup ---
def train_meta_learner(base_preds_train, base_preds_test, y_train, y_test):
    # Use Logistic Regression instead of Random Forest
    meta = LogisticRegression(max_iter=1000, random_state=42)
    meta.fit(base_preds_train, y_train)
    y_pred_meta = meta.predict(base_preds_test)
    print("Meta Learner Accuracy:", accuracy_score(y_test, y_pred_meta))
    print("Meta Learner F1 Score:", f1_score(y_test, y_pred_meta))
    return meta

# --- Pipeline for features ---
def run_feature_pipeline(X_selected, y, method_name):
    print(f"\n=== Running models for {method_name} features ===")

    # Ensure all features are numeric
    if isinstance(X_selected, np.ndarray):
        X_selected = pd.DataFrame(X_selected, columns=[f"F{i+1}" for i in range(X_selected.shape[1])])

    X_selected = X_selected.apply(pd.to_numeric, errors='coerce').astype(np.float32)
    if X_selected.isnull().sum().sum() > 0:
        print(" Missing values detected — filling with column mean")
        X_selected = X_selected.fillna(X_selected.mean())

    # Encode target if needed
    from sklearn.preprocessing import LabelEncoder
    if y.dtype == 'O' or isinstance(y.iloc[0], str):
        le = LabelEncoder()
        y_encoded = le.fit_transform(y)
    else:
        y_encoded = y.values

    # Split
    X_train, X_test, y_train, y_test = train_test_split(
        X_selected, y_encoded, test_size=0.2, random_state=42
    )

    # Expand dims for RNN input
    X_train = np.expand_dims(X_train.values, axis=1)
    X_test = np.expand_dims(X_test.values, axis=1)

    # Create model save directory
    save_dir = f"saved_models/{method_name}"
    os.makedirs(save_dir, exist_ok=True)

    models = {
        "LSTM": build_lstm((1, X_train.shape[2])),
        "BiLSTM": build_bilstm((1, X_train.shape[2])),
        "GRU": build_gru((1, X_train.shape[2]))
    }

    base_train_preds, base_test_preds = [], []

    for name, model in models.items():
        print(f"\nTraining {name}...")
        model.fit(X_train, y_train, epochs=20, batch_size=16, verbose=0)
        train_pred = (model.predict(X_train) > 0.5).astype(int)
        test_pred = (model.predict(X_test) > 0.5).astype(int)

        print(f"{name} Accuracy:", accuracy_score(y_test, test_pred))
        print(f"{name} F1 Score:", f1_score(y_test, test_pred))

        # Save the trained neural network
        model.save(f"{save_dir}/{name}.h5")
        print(f"Saved {name} to {save_dir}/{name}.h5")

        base_train_preds.append(train_pred)
        base_test_preds.append(test_pred)

    # Stack for meta-learner
    base_train_preds = np.column_stack(base_train_preds)
    base_test_preds = np.column_stack(base_test_preds)

    # ---- Meta learner as Logistic Regression ----
    meta = LogisticRegression(max_iter=1000, random_state=42)
    meta.fit(base_train_preds, y_train)
    y_pred_meta = meta.predict(base_test_preds)

    print("\n=== Meta Learner Results ===")
    print("Meta Learner Accuracy:", accuracy_score(y_test, y_pred_meta))
    print("Meta Learner F1 Score:", f1_score(y_test, y_pred_meta))

    # Save meta-learner
    meta_path = f"{save_dir}/MetaLearner_LogisticRegression.pkl"
    joblib.dump(meta, meta_path)
    print(f"Saved Meta Learner to {meta_path}")

# Inspect dtypes of the selected features
selected = top_mi_features['Feature'].tolist()
X_selected = X[selected]

#  Show datatypes
print("=== Data Types of Selected Features ===")
print(X_selected.dtypes)
print("\n")

#  Show columns that are not numeric
non_numeric_cols = X_selected.select_dtypes(exclude=['number']).columns.tolist()
print("=== Non-numeric Columns (Potential Issue) ===")
print(non_numeric_cols)

#  Peek at problematic columns
if len(non_numeric_cols) > 0:
    print("\n=== Sample values from problematic columns ===")
    for col in non_numeric_cols:
        print(f"\nColumn: {col}")
        print(X_selected[col].unique()[:10])

run_feature_pipeline(X[selected_features_rfe], y, "RFE")